Intly 4532
aerogear/mobile-walkthrough pull request #33
Opened 2020-01-08 11:58 UTC by briandooley

2020-01-09 17:44 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +. Make sure you have access to a realm in the link:{sso-realm-url}[{customer-sso-name}, window="_blank"]. If you do not, you can ask your customer-admin user to create one for you.
this seems wrong?

2020-01-09 21:02 UTC, briandooley commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +. Make sure you have access to a realm in the link:{sso-realm-url}[{customer-sso-name}, window="_blank"]. If you do not, you can ask your customer-admin user to create one for you.
Still a draft PR, not ready for review yet.

2020-01-10 12:52 UTC, briandooley commented
@pwright Can you review please?

@jhellar I've noticed, when I attempted to perform step 4 of this walkthough, that the aerogear app freezes when I run it on safari or chrome on IOS 13 in airplane mode.  Can QE take a look ?

2020-01-10 13:08 UTC, jhellar commented
@briandooley ok, will take a look

2020-01-10 14:26 UTC, jhellar commented
@briandooley I've reported the issue in https://issues.redhat.com/browse/INTLY-4813

2020-01-10 15:31 UTC, pwright requested changes
some comments

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +. Go to the link:{route-ionic-showcase-server-host}[newly created client app, window="_blank"]
```suggestion
. Navigate to the link:{route-ionic-showcase-server-host}[Data Sync application user interface, window="_blank"]
```

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +. Make sure you have access to a realm in the link:{sso-realm-url}[{customer-sso-name}, window="_blank"]. If you do not, you can ask your customer-admin user to create one for you.
don't think we need this step? it's like 'make sure RH haven't messed up'

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +You can use the build-in GraphQL playground to interact with the server API. Navigate to the link:{route-ionic-showcase-server-host}/graphql[GraphQL playground, window="_blank"] and remove any text i
```suggestion
. Navigate to the link:{route-ionic-showcase-server-host}/graphql[GraphQL playground, window="_blank"] and replace the text in the left pane of the screen with the following query and mutation::
```

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
>  * `postgresql` - a database
```suggestion
* `postgresql` - a database
+
Once the pods are running, you can use the GraphQL playground to interact with the server API as described in the next step.
```

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +.. Click on the *Installation* tab, and select `Keycloak OIDC JSON` format. Use the `Download` button to save the configuration file to a directory on the computer.
```suggestion
.. Click on the *Installation* tab, and select `Keycloak OIDC JSON` format. Use the `Download` button to save the `keycloak.json` configuration file.
```

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +.. For *Value*, click *Browse* and load the json file that you downloaded previously.
switched from first order list to second order for no good reason?

2020-01-10 15:31 UTC, pwright commented on walkthroughs/1-ionic-showcase/walkthrough.adoc
> +. Navigate to the {openshift-host}/console/project/{walkthrough-namespace}/browse/routes[Routes page of the OpenShift console]
can replace all this with 

Navigate to the link:{route-ionic-showcase-server-host}[Data Sync user interface]

2020-01-10 16:08 UTC, briandooley commented
@pwright Changes made, review again pur-lease?

2020-01-10 16:39 UTC, pwright approved these changes

2020-01-10 16:40 UTC, merged